-- SPDX-License-Identifier: GPL-3.0-or-later
-- SPDX-FileCopyrightText: 2026 Sarah Aronson <v@pingas.org>
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;
use IEEE.std_logic_textio.all;

use work.pProc_bus_gba.all;

-- 2P memory-profile reproduction bench: both gba_top cores in the exact
-- GBA2P configuration (ewram_in_sdram = '1'), served by the REAL SDRAM
-- request cluster from rtl/gba_wrap.vhd -- memorymux_extern for core 1's
-- cart, gba_mem_ewram_sdram for both cores' EWRAM, gba_mem_cart2_sdram for
-- core 2's cart, and gba_wrap's verbatim guest-channel arbitration -- with a
-- behavioral model of rtl/sdram.sv's ch2 port (same request/ready16/ready32/
-- cancel/refresh handshake and latencies) standing in for the PHY.
--
-- Purpose: reproduce the hardware observation "2P build: GBA 1 paints one
-- frame then clean-freezes, GBA 2 never gets going" with full visibility.
-- Hang watchdogs on every cart/EWRAM handshake report the exact stuck
-- transaction and the arbitration state.
--
-- run: sim/run_gba2p_sdram_tb.sh   (ROM via $GBA_ROM, default Apotris)

entity tb_gba2p_sdram is
   generic
   (
      ROM_WORDS : integer := 1048576;
      ROM_HEX   : string  := "sim/tests/rom2_words.hex";
      -- '1' runs the cores unpaced (GBA_cputurbo) to shorten boot-copy phases;
      -- timing fidelity drops, use only for data-corruption repros
      TURBO : std_logic := '0';
      -- '1' models a 512-column SDRAM chip (W9825 class, 32MB): column bit 9
      -- is ignored during CAS, so sdram.sv's {..., ch2_rnw, addr[25:1]}
      -- packing silently aliases byte-address bit 25 -- which folds the 2P
      -- EWRAM slots at 0x2080000/0x20C0000 onto the ROM image at 0x80000
      ALIAS_32MB : std_logic := '0'
   );
end entity;

architecture sim of tb_gba2p_sdram is

   -- clk6x is the SDRAM/scheduler clock, clk1x the core clock, ratio 6 with
   -- coincident rising edges every clk1x period, as generated by the PLL
   constant CLK6X_PERIOD : time := 10 ns;
   constant CLK1X_PERIOD : time := 60 ns;

   signal clk1x : std_logic := '0';
   signal clk6x : std_logic := '0';

   -- clk6xIndex generation copied from rtl/gba_wrap.vhd
   signal clk1xToggle    : std_logic := '0';
   signal clk1xToggle6x  : std_logic := '0';
   signal clk1xToggle6x_1: std_logic := '0';
   signal clk6xIndex     : unsigned(2 downto 0) := (others => '0');

   -- ------------------------------------------------------------------
   -- SDRAM layout, byte addresses, matching GBA.sv's gba_wrap generics
   -- ------------------------------------------------------------------
   constant Softmap_GBA_Gamerom_ADDR : integer := 524288;
   constant Softmap_GBA_EWRAM_ADDR   : integer := 34078720;
   constant Softmap_GBA_EWRAM2_ADDR  : integer := 34340864;

   constant BIOS_WORDS : integer := 4096;

   type t_word_array is array (natural range <>) of std_logic_vector(31 downto 0);
   type t_hw_array   is array (natural range <>) of std_logic_vector(15 downto 0);

   -- backing store, halfword granular like the real 16bit SDRAM
   shared variable rom_hw : t_hw_array(0 to 2*ROM_WORDS - 1);
   shared variable ew1_hw : t_hw_array(0 to 131071) := (others => (others => '0'));
   shared variable ew2_hw : t_hw_array(0 to 131071) := (others => (others => '0'));
   shared variable bios_image : t_word_array(0 to BIOS_WORDS - 1);

   impure function load_hexwords(path : string; max_words : integer) return t_word_array is
      file     f       : text;
      variable ln      : line;
      variable words   : t_word_array(0 to max_words - 1) := (others => (others => '0'));
      variable i       : integer := 0;
      variable hexword : std_logic_vector(31 downto 0);
      variable ok      : boolean;
   begin
      file_open(f, path, read_mode);
      while not endfile(f) and i < max_words loop
         readline(f, ln);
         hread(ln, hexword, ok);
         assert ok report "hread failed on " & path severity failure;
         words(i) := hexword;
         i := i + 1;
      end loop;
      file_close(f);
      report path & ": loaded " & integer'image(i) & " words";
      return words;
   end function;

   -- ------------------------------------------------------------------
   -- gba_top <-> memory cluster wiring, names follow gba_wrap
   -- ------------------------------------------------------------------
   signal GBA_on : std_logic := '0';

   signal bios_wraddr : std_logic_vector(11 downto 0) := (others => '0');
   signal bios_wrdata : std_logic_vector(31 downto 0) := (others => '0');
   signal bios_wr     : std_logic := '0';

   -- core 1 cart bus (served by memorymux_extern)
   signal cart_ena, cart_idle, cart_32, cart_rnw, cart_done : std_logic;
   signal cart_addr      : std_logic_vector(27 downto 0);
   signal cart_writedata : std_logic_vector(7 downto 0);
   signal cart_readdata  : std_logic_vector(31 downto 0);
   signal cart_waitcnt   : std_logic_vector(15 downto 0);
   signal cart_reset     : std_logic;
   signal dma_eepromcount: unsigned(16 downto 0);
   signal flash_busy     : std_logic;
   signal error_refresh  : std_logic;

   -- core 2 cart bus (served by gba_mem_cart2_sdram)
   signal c2_cart_ena, c2_cart_32, c2_cart_rnw, c2_cart_done : std_logic;
   signal c2_cart_addr     : std_logic_vector(27 downto 0);
   signal c2_cart_readdata : std_logic_vector(31 downto 0);
   signal c2_cart_reset    : std_logic;

   -- EWRAM buses
   signal ewram_ena, ewram_rnw, ewram_done : std_logic;
   signal ewram_addr      : std_logic_vector(15 downto 0);
   signal ewram_be        : std_logic_vector(3 downto 0);
   signal ewram_writedata : std_logic_vector(31 downto 0);
   signal ewram_readdata  : std_logic_vector(31 downto 0);

   signal ew2_ena, ew2_rnw, ew2_done : std_logic;
   signal ew2_addr      : std_logic_vector(15 downto 0);
   signal ew2_be        : std_logic_vector(3 downto 0);
   signal ew2_writedata : std_logic_vector(31 downto 0);
   signal ew2_readdata  : std_logic_vector(31 downto 0);

   -- guest channel arbitration (verbatim signal set from gba_wrap)
   signal guests_active, guests_busy, extern_allow : std_logic;
   signal ewram_active, ewram_busy, ew1_allow      : std_logic;
   signal ew2_active, ew2_busy, ew2_allow          : std_logic;
   signal cart2_active, cart2_busy, cart2_allow    : std_logic;

   -- shared SDRAM request port (gba_wrap's mux outputs)
   signal mmx_sdram_Din : std_logic_vector(31 downto 0);
   signal mmx_sdram_Adr : std_logic_vector(26 downto 0);
   signal mmx_sdram_rnw : std_logic;
   signal mmx_sdram_ena : std_logic;

   signal ew_sdram_ena, ew_sdram_rnw   : std_logic;
   signal ew_sdram_Adr  : std_logic_vector(26 downto 0);
   signal ew_sdram_Din  : std_logic_vector(31 downto 0);
   signal ew_sdram_be   : std_logic_vector(3 downto 0);

   signal ew2_sdram_ena, ew2_sdram_rnw : std_logic;
   signal ew2_sdram_Adr : std_logic_vector(26 downto 0);
   signal ew2_sdram_Din : std_logic_vector(31 downto 0);
   signal ew2_sdram_be  : std_logic_vector(3 downto 0);

   signal c2_sdram_ena  : std_logic;
   signal c2_sdram_Adr  : std_logic_vector(26 downto 0);

   signal sdram_ena, sdram_rnw     : std_logic;
   signal sdram_Adr     : std_logic_vector(26 downto 0);
   signal sdram_Din     : std_logic_vector(31 downto 0);
   signal sdram_be      : std_logic_vector(3 downto 0);
   signal sdram_cancel  : std_logic;
   signal sdram_refresh : std_logic;
   signal sdram_Dout    : std_logic_vector(31 downto 0) := (others => '0');
   signal sdram_done16  : std_logic := '0';
   signal sdram_done32  : std_logic := '0';

   constant SAVESTATE_BUS_ZERO : proc_bus_gb_type :=
      (Din => (others => '0'), Adr => (others => '0'), rnw => '1',
       ena => '0', acc => "00", bEna => (others => '0'), rst => '0');

   -- link cable, cross-wired like gba_wrap's internal 2P link
   signal c1_link_clk_out, c1_link_clk_oe, c1_link_clk_in : std_logic;
   signal c1_link_so_out,  c1_link_so_oe,  c1_link_si_in  : std_logic;
   signal c1_link_sd_out,  c1_link_sd_oe,  c1_link_sd_in  : std_logic;
   signal c2_link_clk_out, c2_link_clk_oe, c2_link_clk_in : std_logic;
   signal c2_link_so_out,  c2_link_so_oe,  c2_link_si_in  : std_logic;
   signal c2_link_sd_out,  c2_link_sd_oe,  c2_link_sd_in  : std_logic;
   signal l_sc, l_sd, l_si_c1, l_si_c2 : std_logic := '1';
   signal l_so_c2 : std_logic := '1'; -- core 2's own SO level (for the wire monitor; c1's SI is cable-grounded)

   signal c1_vblank, c2_vblank : std_logic;
   signal c1_px_we, c2_px_we   : std_logic;
   signal c1_px_x,  c2_px_x    : integer range 0 to 239;
   signal c1_px_y,  c2_px_y    : integer range 0 to 159;

   signal c1_export, c2_export : work.pexport.cpu_export_type;

   constant ZERO28 : std_logic_vector(27 downto 0) := (others => '0');
   constant ZERO32 : std_logic_vector(31 downto 0) := (others => '0');
   constant ZERO64 : std_logic_vector(63 downto 0) := (others => '0');

begin

   clk6x <= not clk6x after CLK6X_PERIOD / 2;
   clk1x <= not clk1x after CLK1X_PERIOD / 2;

   -- clk6xIndex sync, verbatim from gba_wrap
   process (clk1x)
   begin
      if rising_edge(clk1x) then
         clk1xToggle <= not clk1xToggle;
      end if;
   end process;

   process (clk6x)
   begin
      if rising_edge(clk6x) then
         clk1xToggle6x   <= clk1xToggle;
         clk1xToggle6x_1 <= clk1xToggle6x;
         if (clk1xToggle6x = '1' and clk1xToggle6x_1 = '0') then
            clk6xIndex <= "010";
         elsif (clk6xIndex = 5) then
            clk6xIndex <= (others => '0');
         else
            clk6xIndex <= clk6xIndex + 1;
         end if;
      end if;
   end process;

   -- ==================================================================
   -- image loading + BIOS injection + reset release
   -- ==================================================================
   preload : process
      variable words : t_word_array(0 to ROM_WORDS - 1);
   begin
      words := load_hexwords(ROM_HEX, ROM_WORDS);
      for i in 0 to ROM_WORDS - 1 loop
         rom_hw(2*i)     := words(i)(15 downto 0);
         rom_hw(2*i + 1) := words(i)(31 downto 16);
      end loop;
      bios_image := load_hexwords("sim/tests/bios_words.hex", BIOS_WORDS);
      wait;
   end process;

   biosload : process
   begin
      wait for 100 ns;
      wait until rising_edge(clk1x);
      for i in 0 to BIOS_WORDS - 1 loop
         bios_wraddr <= std_logic_vector(to_unsigned(i, 12));
         bios_wrdata <= bios_image(i);
         bios_wr     <= '1';
         wait until rising_edge(clk1x);
      end loop;
      bios_wr <= '0';
      report "BIOS loaded into both cores";
      wait for 100 ns;
      GBA_on <= '1';
      wait;
   end process;

   -- ==================================================================
   -- guest channel arbitration + request mux, verbatim from gba_wrap
   -- ==================================================================
   guests_active <= ewram_active or ew2_active or cart2_active;
   guests_busy   <= ewram_busy   or ew2_busy   or cart2_busy;

   ew1_allow     <= extern_allow and (not ew2_busy)     and (not cart2_busy);
   ew2_allow     <= extern_allow and (not ewram_active) and (not cart2_busy);
   cart2_allow   <= extern_allow and (not ewram_active) and (not ew2_active);

   sdram_ena <= mmx_sdram_ena or ew_sdram_ena or ew2_sdram_ena or c2_sdram_ena;
   sdram_rnw <= ew_sdram_rnw  when (ewram_busy = '1') else
                ew2_sdram_rnw when (ew2_busy   = '1') else
                '1'           when (cart2_busy = '1') else
                mmx_sdram_rnw;
   sdram_Adr <= ew_sdram_Adr  when (ewram_busy = '1') else
                ew2_sdram_Adr when (ew2_busy   = '1') else
                c2_sdram_Adr  when (cart2_busy = '1') else
                mmx_sdram_Adr;
   sdram_Din <= ew_sdram_Din  when (ewram_busy = '1') else
                ew2_sdram_Din when (ew2_busy   = '1') else
                mmx_sdram_Din;
   sdram_be  <= ew_sdram_be   when (ewram_busy = '1') else
                ew2_sdram_be  when (ew2_busy   = '1') else
                "1111";

   -- ==================================================================
   -- behavioral rtl/sdram.sv ch2 port: same handshake and latencies
   -- ==================================================================
   sdram_model : block
      type t_state is (S_IDLE, S_WAIT, S_RW1, S_RW2, S_IDLE5, S_IDLE4, S_IDLE3, S_IDLE2, S_IDLE1, S_RFSH5, S_RFSH4, S_RFSH3, S_RFSH2, S_RFSH1, S_RFSH0);
      signal state       : t_state := S_IDLE;
      signal rq          : std_logic := '0';
      signal saved_wr    : std_logic;
      signal saved_adr   : std_logic_vector(26 downto 0);
      signal saved_din   : std_logic_vector(31 downto 0);
      signal saved_be    : std_logic_vector(3 downto 0);
      signal delay       : std_logic_vector(6 downto 0) := (others => '0');
      signal pend_lo, pend_hi : std_logic_vector(15 downto 0);
      signal refresh_cnt : integer := 0;

      -- FIXED sdram.sv ch2 contract: attributes latch at the request pulse
      -- (live only for a same-edge grant), cancel clears a pending rq and
      -- sticks for an op between grant and CAS
      signal ena_adr : std_logic_vector(26 downto 0);
      signal ena_rnw : std_logic;
      signal ena_din : std_logic_vector(31 downto 0);
      signal ena_be  : std_logic_vector(3 downto 0);
      signal kill    : std_logic := '0';

      impure function fold(byteaddr : integer) return integer is
      begin
         if (ALIAS_32MB = '1' and byteaddr >= 33554432) then
            return byteaddr - 33554432; -- column bit 9 dropped by the chip
         end if;
         return byteaddr;
      end function;

      impure function read_hw(byteaddr_in : integer) return std_logic_vector is
         variable byteaddr : integer;
      begin
         byteaddr := fold(byteaddr_in);
         if (byteaddr >= Softmap_GBA_Gamerom_ADDR and byteaddr < Softmap_GBA_Gamerom_ADDR + 4*ROM_WORDS) then
            return rom_hw((byteaddr - Softmap_GBA_Gamerom_ADDR) / 2);
         elsif (byteaddr >= Softmap_GBA_EWRAM_ADDR and byteaddr < Softmap_GBA_EWRAM_ADDR + 262144) then
            return ew1_hw((byteaddr - Softmap_GBA_EWRAM_ADDR) / 2);
         elsif (byteaddr >= Softmap_GBA_EWRAM2_ADDR and byteaddr < Softmap_GBA_EWRAM2_ADDR + 262144) then
            return ew2_hw((byteaddr - Softmap_GBA_EWRAM2_ADDR) / 2);
         else
            return x"FFFF"; -- unmapped: open bus, like reading past the image
         end if;
      end function;

      procedure write_hw(byteaddr_in : integer; data : std_logic_vector(15 downto 0); benable : std_logic_vector(1 downto 0)) is
         variable cur : std_logic_vector(15 downto 0);
         variable idx : integer;
         variable byteaddr : integer;
      begin
         if (benable = "00") then return; end if;
         byteaddr := fold(byteaddr_in);
         if (ALIAS_32MB = '1' and byteaddr >= Softmap_GBA_Gamerom_ADDR and byteaddr < Softmap_GBA_Gamerom_ADDR + 4*ROM_WORDS) then
            -- aliased EWRAM traffic lands in the ROM image: the chip happily
            -- writes it, exactly like real silicon would
            idx := (byteaddr - Softmap_GBA_Gamerom_ADDR) / 2;
            cur := rom_hw(idx);
            if (benable(0) = '1') then cur(7 downto 0)  := data(7 downto 0);  end if;
            if (benable(1) = '1') then cur(15 downto 8) := data(15 downto 8); end if;
            rom_hw(idx) := cur;
         elsif (byteaddr >= Softmap_GBA_EWRAM_ADDR and byteaddr < Softmap_GBA_EWRAM_ADDR + 262144) then
            idx := (byteaddr - Softmap_GBA_EWRAM_ADDR) / 2;
            cur := ew1_hw(idx);
            if (benable(0) = '1') then cur(7 downto 0)  := data(7 downto 0);  end if;
            if (benable(1) = '1') then cur(15 downto 8) := data(15 downto 8); end if;
            ew1_hw(idx) := cur;
         elsif (byteaddr >= Softmap_GBA_EWRAM2_ADDR and byteaddr < Softmap_GBA_EWRAM2_ADDR + 262144) then
            idx := (byteaddr - Softmap_GBA_EWRAM2_ADDR) / 2;
            cur := ew2_hw(idx);
            if (benable(0) = '1') then cur(7 downto 0)  := data(7 downto 0);  end if;
            if (benable(1) = '1') then cur(15 downto 8) := data(15 downto 8); end if;
            ew2_hw(idx) := cur;
         else
            report "SDRAM write to unmapped/readonly byteaddr 0x" &
                   to_hstring(to_unsigned(byteaddr, 27)) severity warning;
         end if;
      end procedure;

   begin

      process (clk6x)
         variable a : integer;
      begin
         if rising_edge(clk6x) then

            rq <= (rq and not sdram_cancel) or sdram_ena;
            sdram_done16 <= '0';
            sdram_done32 <= '0';

            if (sdram_ena = '1') then
               ena_adr <= sdram_Adr;
               ena_rnw <= sdram_rnw;
               ena_din <= sdram_Din;
               ena_be  <= sdram_be;
            end if;

            -- data-ready shift pipeline, sdram.sv's data_ready_delay2
            delay <= '0' & delay(6 downto 1);
            if (delay(3) = '1') then
               sdram_Dout(15 downto 0) <= pend_lo;
               sdram_done16            <= '1';
            end if;
            if (delay(2) = '1') then
               sdram_Dout(31 downto 16) <= pend_hi;
               sdram_done32             <= '1';
            end if;

            refresh_cnt <= refresh_cnt + 1;

            case (state) is

               when S_IDLE =>
                  if (sdram_refresh = '1' or refresh_cnt > 750) then
                     state       <= S_RFSH5;
                     refresh_cnt <= 0;
                  elsif (rq = '1' or sdram_ena = '1') then
                     if (sdram_ena = '1') then
                        saved_adr <= sdram_Adr;
                        saved_din <= sdram_Din;
                        saved_be  <= sdram_be;
                        saved_wr  <= not sdram_rnw;
                     else
                        saved_adr <= ena_adr;
                        saved_din <= ena_din;
                        saved_be  <= ena_be;
                        saved_wr  <= not ena_rnw;
                     end if;
                     rq        <= '0';
                     kill      <= '0';
                     state     <= S_WAIT;
                  end if;

               when S_WAIT => state <= S_RW1;

               when S_RW1 =>
                  a := to_integer(unsigned(saved_adr(26 downto 1) & '0'));
                  if (saved_wr = '1') then
                     write_hw(a, saved_din(15 downto 0), saved_be(1 downto 0));
                     state <= S_RW2;
                  else
                     pend_lo  <= read_hw(a);
                     pend_hi  <= read_hw(a + 2);
                     if (kill = '0') then
                        delay(6) <= '1';
                     end if;
                     state    <= S_IDLE5;
                  end if;

               when S_RW2 =>
                  a := to_integer(unsigned(saved_adr(26 downto 1) & '0'));
                  write_hw(a + 2, saved_din(31 downto 16), saved_be(3 downto 2));
                  sdram_done16 <= '1';
                  sdram_done32 <= '1';
                  -- 8-cycle write slot, matching the fixed sdram.sv (tRC/tDAL
                  -- guard: same-bank ACT may not follow a write within 63ns)
                  state        <= S_IDLE4;

               when S_IDLE5 => state <= S_IDLE4;
               when S_IDLE4 => state <= S_IDLE3;
               when S_IDLE3 => state <= S_IDLE2;
               when S_IDLE2 => state <= S_IDLE1;
               when S_IDLE1 => state <= S_IDLE;

               when S_RFSH5 => state <= S_RFSH4;
               when S_RFSH4 => state <= S_RFSH3;
               when S_RFSH3 => state <= S_RFSH2;
               when S_RFSH2 => state <= S_RFSH1;
               when S_RFSH1 => state <= S_RFSH0;
               when S_RFSH0 => state <= S_IDLE;

            end case;

            if (sdram_cancel = '1') then
               delay        <= (others => '0');
               sdram_done16 <= '0'; -- incl. a done registered this very edge
               sdram_done32 <= '0';
               if (sdram_ena = '0') then -- a same-edge relaunch keeps its op
                  kill <= '1';           -- last assignment: wins over grant
               end if;
            end if;

         end if;
      end process;

   end block;

   -- ==================================================================
   -- core 1 memory cluster: the real memorymux_extern + EWRAM channel
   -- ==================================================================
   iextern : entity work.memorymux_extern
   generic map
   (
      is_simu                  => '1',
      Softmap_GBA_Gamerom_ADDR => Softmap_GBA_Gamerom_ADDR,
      Softmap_GBA_FLASH_ADDR   => 0,
      Softmap_GBA_EEPROM_ADDR  => 0
   )
   port map
   (
      clk1x                => clk1x,
      clk6x                => clk6x,
      clk6xIndex           => clk6xIndex,
      reset                => cart_reset,

      SramFlashEnable      => '0',

      error_refresh        => error_refresh,
      flash_busy           => flash_busy,

      savestate_bus        => SAVESTATE_BUS_ZERO,
      ss_wired_out         => open,
      ss_wired_done        => open,

      cart_ena             => cart_ena,
      cart_idle            => cart_idle,
      cart_32              => cart_32,
      cart_rnw             => cart_rnw,
      cart_addr            => cart_addr,
      cart_writedata       => cart_writedata,
      cart_done            => cart_done,
      cart_readdata        => cart_readdata,

      cart_waitcnt         => cart_waitcnt,

      ewram_active         => guests_active,
      ewram_allow          => extern_allow,
      hold_ena             => guests_busy,

      sdram_Din            => mmx_sdram_Din,
      sdram_Adr            => mmx_sdram_Adr,
      sdram_rnw            => mmx_sdram_rnw,
      sdram_ena            => mmx_sdram_ena,
      sdram_cancel         => sdram_cancel,
      sdram_refresh        => sdram_refresh,
      sdram_Dout           => sdram_Dout,
      sdram_done16         => sdram_done16,
      sdram_done32         => sdram_done32,

      specialmodule        => '0',
      GPIO_readEna         => open,
      GPIO_done            => '0',
      GPIO_Din             => "0000",
      GPIO_Dout            => open,
      GPIO_writeEna        => open,
      GPIO_addr            => open,

      dma_eepromcount      => dma_eepromcount,
      flash_1m             => '0',
      MaxPakAddr           => std_logic_vector(to_unsigned(ROM_WORDS, 25)),
      memory_remap         => '0',

      save_eeprom          => open,
      save_sram            => open,
      save_flash           => open,

      tilt                 => '0',
      AnalogTiltX          => (others => '0'),
      AnalogTiltY          => (others => '0')
   );

   iewram_sdram : entity work.gba_mem_ewram_sdram
   generic map
   (
      Softmap_GBA_EWRAM_ADDR => Softmap_GBA_EWRAM_ADDR
   )
   port map
   (
      clk1x           => clk1x,
      clk6x           => clk6x,
      clk6xIndex      => clk6xIndex,
      reset           => cart_reset,

      ewram_ena       => ewram_ena,
      ewram_rnw       => ewram_rnw,
      ewram_addr      => ewram_addr,
      ewram_be        => ewram_be,
      ewram_writedata => ewram_writedata,
      ewram_done      => ewram_done,
      ewram_readdata  => ewram_readdata,

      ewram_allow     => ew1_allow,
      ewram_active    => ewram_active,
      ewram_busy      => ewram_busy,

      ew_sdram_ena    => ew_sdram_ena,
      ew_sdram_rnw    => ew_sdram_rnw,
      ew_sdram_Adr    => ew_sdram_Adr,
      ew_sdram_Din    => ew_sdram_Din,
      ew_sdram_be     => ew_sdram_be,
      sdram_Dout      => sdram_Dout,
      sdram_done32    => sdram_done32
   );

   -- ==================================================================
   -- core 2 memory cluster
   -- ==================================================================
   iewram2_sdram : entity work.gba_mem_ewram_sdram
   generic map
   (
      Softmap_GBA_EWRAM_ADDR => Softmap_GBA_EWRAM2_ADDR
   )
   port map
   (
      clk1x           => clk1x,
      clk6x           => clk6x,
      clk6xIndex      => clk6xIndex,
      reset           => c2_cart_reset,

      ewram_ena       => ew2_ena,
      ewram_rnw       => ew2_rnw,
      ewram_addr      => ew2_addr,
      ewram_be        => ew2_be,
      ewram_writedata => ew2_writedata,
      ewram_done      => ew2_done,
      ewram_readdata  => ew2_readdata,

      ewram_allow     => ew2_allow,
      ewram_active    => ew2_active,
      ewram_busy      => ew2_busy,

      ew_sdram_ena    => ew2_sdram_ena,
      ew_sdram_rnw    => ew2_sdram_rnw,
      ew_sdram_Adr    => ew2_sdram_Adr,
      ew_sdram_Din    => ew2_sdram_Din,
      ew_sdram_be     => ew2_sdram_be,
      sdram_Dout      => sdram_Dout,
      sdram_done32    => sdram_done32
   );

   icart2_sdram : entity work.gba_mem_cart2_sdram
   generic map
   (
      Softmap_GBA_Gamerom_ADDR => Softmap_GBA_Gamerom_ADDR
   )
   port map
   (
      clk1x           => clk1x,
      clk6x           => clk6x,
      clk6xIndex      => clk6xIndex,
      reset           => c2_cart_reset,

      memory_remap    => '0',
      MaxPakAddr      => std_logic_vector(to_unsigned(ROM_WORDS, 25)),

      cart_ena        => c2_cart_ena,
      cart_32         => c2_cart_32,
      cart_rnw        => c2_cart_rnw,
      cart_addr       => c2_cart_addr,
      cart_done       => c2_cart_done,
      cart_readdata   => c2_cart_readdata,

      cart_allow      => cart2_allow,
      cart_active     => cart2_active,
      cart_busy       => cart2_busy,

      c2_sdram_ena    => c2_sdram_ena,
      c2_sdram_Adr    => c2_sdram_Adr,
      sdram_Dout      => sdram_Dout,
      sdram_done32    => sdram_done32
   );

   -- ==================================================================
   -- internal link cable, registered wired-AND + crossed SO/SI
   -- ==================================================================
   process (clk1x)
   begin
      if rising_edge(clk1x) then
         l_sc    <= (c1_link_clk_out or not c1_link_clk_oe) and (c2_link_clk_out or not c2_link_clk_oe);
         l_sd    <= (c1_link_sd_out  or not c1_link_sd_oe ) and (c2_link_sd_out  or not c2_link_sd_oe );
         l_si_c1 <= '0'; -- real cable: 1P plug grounds SI (that's what makes core 1 the master)
         l_so_c2 <= (c2_link_so_out  or not c2_link_so_oe );
         l_si_c2 <= (c1_link_so_out  or not c1_link_so_oe );
      end if;
   end process;

   c1_link_clk_in <= l_sc;
   c1_link_si_in  <= l_si_c1;
   c1_link_sd_in  <= l_sd;
   c2_link_clk_in <= l_sc;
   c2_link_si_in  <= l_si_c2;
   c2_link_sd_in  <= l_sd;

   -- SIO wire monitor: decode 16-bit multiplayer frames off the cable.
   -- Data changes on SC falling, both ends sample on rising: sample there.
   -- LSB travels first on the real wire, so frames assemble from the right.
   siomon : process (clk1x)
      variable sc_1        : std_logic := '1';
      variable bits        : integer := 0;
      variable idle        : integer := 0;
      variable parent_word : std_logic_vector(15 downto 0) := (others => '0');
      variable child_word  : std_logic_vector(15 downto 0) := (others => '0');
      variable frames      : integer := 0;
   begin
      if rising_edge(clk1x) then
         if (sc_1 = '0' and l_sc = '1') then
            parent_word := l_si_c2 & parent_word(15 downto 1); -- core 1's SO
            child_word  := l_so_c2 & child_word(15 downto 1);  -- core 2's SO
            bits := bits + 1;
            idle := 0;
            if (bits = 16) then
               frames := frames + 1;
               report "SIO frame " & integer'image(frames) &
                      ": parent " & to_hstring(parent_word) &
                      " child " & to_hstring(child_word);
               bits := 0;
            end if;
         elsif (bits > 0) then
            idle := idle + 1;
            if (idle > 5000) then -- ~300us without a clock edge: dead exchange
               report "SIO PARTIAL frame, " & integer'image(bits) & " bits"
                      severity warning;
               bits := 0;
               idle := 0;
            end if;
         end if;
         sc_1 := l_sc;
      end if;
   end process;

   -- ==================================================================
   -- the two cores, 2P profile generics
   -- ==================================================================
   icore1 : entity work.gba_top
   generic map
   (
      Softmap_GBA_Gamerom_ADDR => Softmap_GBA_Gamerom_ADDR,
      Softmap_GBA_FLASH_ADDR   => 0,
      Softmap_GBA_EEPROM_ADDR  => 0,
      Softmap_SaveState_ADDR   => 0,
      Softmap_Rewind_ADDR      => 0,
      is_simu                  => '1',
      simu_export_trace        => '0',
      strip_savestates         => '1',
      strip_cheats             => '1',
      ewram_in_sdram           => '1',
      turbosound               => '0'
   )
   port map
   (
      clk1x                 => clk1x,
      GBA_on                => GBA_on,
      pause                 => '0',
      allowUnpause          => '1',
      inPause               => open,
      GBA_lockspeed         => '1',
      GBA_cputurbo          => TURBO,
      GBA_flash_1m          => '0',
      Underclock            => "00",
      CyclesMissing         => open,
      CyclesVsyncSpeed      => open,
      increaseSSHeaderCount => '0',
      save_state            => '0',
      load_state            => '0',
      interframe_blend      => "00",
      shade_mode            => "000",
      rewind_on             => '0',
      rewind_active         => '0',
      savestate_number      => 0,

      error_cpu             => open,
      error_memRequ_timeout => open,
      error_memResp_timeout => open,
      flash_busy            => flash_busy,

      cheat_clear           => '0',
      cheats_enabled        => '0',
      cheat_on              => '0',
      cheat_in              => (others => '0'),
      cheats_active         => open,

      cart_ena              => cart_ena,
      cart_idle             => cart_idle,
      cart_32               => cart_32,
      cart_rnw              => cart_rnw,
      cart_addr             => cart_addr,
      cart_writedata        => cart_writedata,
      cart_done             => cart_done,
      cart_readdata         => cart_readdata,
      cart_waitcnt          => cart_waitcnt,
      dma_eepromcount       => dma_eepromcount,
      cart_reset            => cart_reset,

      ewram_ena             => ewram_ena,
      ewram_rnw             => ewram_rnw,
      ewram_addr            => ewram_addr,
      ewram_be              => ewram_be,
      ewram_writedata       => ewram_writedata,
      ewram_done            => ewram_done,
      ewram_readdata        => ewram_readdata,

      SAVE_out_Din          => open,
      SAVE_out_Dout         => ZERO64,
      SAVE_out_Adr          => open,
      SAVE_out_rnw          => open,
      SAVE_out_ena          => open,
      SAVE_out_active       => open,
      SAVE_out_be           => open,
      SAVE_out_done         => '0',
      savestate_bus_ext     => open,
      ss_wired_out_ext      => ZERO32,
      ss_wired_done_ext     => '0',

      bios_wraddr           => bios_wraddr,
      bios_wrdata           => bios_wrdata,
      bios_wr               => bios_wr,

      load_done             => open,

      KeyA                  => '0',
      KeyB                  => '0',
      KeySelect             => '0',
      KeyStart              => '0',
      KeyRight              => '0',
      KeyLeft               => '0',
      KeyUp                 => '0',
      KeyDown               => '0',
      KeyR                  => '0',
      KeyL                  => '0',
      KeyPause              => '0',

      link_enable           => '1',
      link_clk_out          => c1_link_clk_out,
      link_clk_oe           => c1_link_clk_oe,
      link_clk_in           => c1_link_clk_in,
      link_so_out           => c1_link_so_out,
      link_so_oe            => c1_link_so_oe,
      link_si_in            => c1_link_si_in,
      link_sd_out           => c1_link_sd_out,
      link_sd_oe            => c1_link_sd_oe,
      link_sd_in            => c1_link_sd_in,

      GBA_BusAddr           => ZERO28,
      GBA_BusRnW            => '1',
      GBA_BusACC            => "01",
      GBA_BusWriteData      => ZERO32,
      GBA_BusReadData       => open,
      GBA_Bus_written       => '0',

      pixel_out_x           => c1_px_x,
      pixel_out_y           => c1_px_y,
      pixel_out_addr        => open,
      pixel_out_data        => open,
      pixel_out_we          => c1_px_we,
      vblank_trigger        => c1_vblank,

      sound_out_left        => open,
      sound_out_right       => open,

      debug_cpu_pc          => open,
      debug_cpu_mixed       => open,
      debug_irq             => open,
      debug_dma             => open,
      debug_mem             => open
   );

   icore2 : entity work.gba_top
   generic map
   (
      Softmap_GBA_Gamerom_ADDR => Softmap_GBA_Gamerom_ADDR,
      Softmap_GBA_FLASH_ADDR   => 0,
      Softmap_GBA_EEPROM_ADDR  => 0,
      Softmap_SaveState_ADDR   => 0,
      Softmap_Rewind_ADDR      => 0,
      is_simu                  => '1',
      simu_export_trace        => '0',
      strip_savestates         => '1',
      strip_cheats             => '1',
      ewram_in_sdram           => '1',
      turbosound               => '0'
   )
   port map
   (
      clk1x                 => clk1x,
      GBA_on                => GBA_on,
      pause                 => '0',
      allowUnpause          => '1',
      inPause               => open,
      GBA_lockspeed         => '1',
      GBA_cputurbo          => TURBO,
      GBA_flash_1m          => '0',
      Underclock            => "00",
      CyclesMissing         => open,
      CyclesVsyncSpeed      => open,
      increaseSSHeaderCount => '0',
      save_state            => '0',
      load_state            => '0',
      interframe_blend      => "00",
      shade_mode            => "000",
      rewind_on             => '0',
      rewind_active         => '0',
      savestate_number      => 0,

      error_cpu             => open,
      error_memRequ_timeout => open,
      error_memResp_timeout => open,
      flash_busy            => '0',

      cheat_clear           => '0',
      cheats_enabled        => '0',
      cheat_on              => '0',
      cheat_in              => (others => '0'),
      cheats_active         => open,

      cart_ena              => c2_cart_ena,
      cart_idle             => open,
      cart_32               => c2_cart_32,
      cart_rnw              => c2_cart_rnw,
      cart_addr             => c2_cart_addr,
      cart_writedata        => open,
      cart_done             => c2_cart_done,
      cart_readdata         => c2_cart_readdata,
      cart_waitcnt          => open,
      dma_eepromcount       => open,
      cart_reset            => c2_cart_reset,

      ewram_ena             => ew2_ena,
      ewram_rnw             => ew2_rnw,
      ewram_addr            => ew2_addr,
      ewram_be              => ew2_be,
      ewram_writedata       => ew2_writedata,
      ewram_done            => ew2_done,
      ewram_readdata        => ew2_readdata,

      SAVE_out_Din          => open,
      SAVE_out_Dout         => ZERO64,
      SAVE_out_Adr          => open,
      SAVE_out_rnw          => open,
      SAVE_out_ena          => open,
      SAVE_out_active       => open,
      SAVE_out_be           => open,
      SAVE_out_done         => '0',
      savestate_bus_ext     => open,
      ss_wired_out_ext      => ZERO32,
      ss_wired_done_ext     => '0',

      bios_wraddr           => bios_wraddr,
      bios_wrdata           => bios_wrdata,
      bios_wr               => bios_wr,

      load_done             => open,

      KeyA                  => '0',
      KeyB                  => '0',
      KeySelect             => '0',
      KeyStart              => '0',
      KeyRight              => '0',
      KeyLeft               => '0',
      KeyUp                 => '0',
      KeyDown               => '0',
      KeyR                  => '0',
      KeyL                  => '0',
      KeyPause              => '0',

      link_enable           => '1',
      link_clk_out          => c2_link_clk_out,
      link_clk_oe           => c2_link_clk_oe,
      link_clk_in           => c2_link_clk_in,
      link_so_out           => c2_link_so_out,
      link_so_oe            => c2_link_so_oe,
      link_si_in            => c2_link_si_in,
      link_sd_out           => c2_link_sd_out,
      link_sd_oe            => c2_link_sd_oe,
      link_sd_in            => c2_link_sd_in,

      GBA_BusAddr           => ZERO28,
      GBA_BusRnW            => '1',
      GBA_BusACC            => "01",
      GBA_BusWriteData      => ZERO32,
      GBA_BusReadData       => open,
      GBA_Bus_written       => '0',

      pixel_out_x           => c2_px_x,
      pixel_out_y           => c2_px_y,
      pixel_out_addr        => open,
      pixel_out_data        => open,
      pixel_out_we          => c2_px_we,
      vblank_trigger        => c2_vblank,

      sound_out_left        => open,
      sound_out_right       => open,

      debug_cpu_pc          => open,
      debug_cpu_mixed       => open,
      debug_irq             => open,
      debug_dma             => open,
      debug_mem             => open
   );

   -- bind the internal cpu state records now that both cores exist
   monitor_bind : block
   begin
      c1_export <= << signal .tb_gba2p_sdram.icore1.cpu_export : work.pexport.cpu_export_type >>;
      c2_export <= << signal .tb_gba2p_sdram.icore2.cpu_export : work.pexport.cpu_export_type >>;
   end block;

   -- ==================================================================
   -- hang watchdogs: every bus handshake must complete within a frame
   -- ==================================================================
   watchdogs : block
      constant HANG_CYCLES : integer := 20000; -- clk1x; any real op is < 100

      procedure dump_arb(prefix : string) is
      begin
         report prefix &
            " | extern_allow=" & std_logic'image(extern_allow) &
            " ew1(a/b)=" & std_logic'image(ewram_active) & std_logic'image(ewram_busy) &
            " ew2(a/b)=" & std_logic'image(ew2_active) & std_logic'image(ew2_busy) &
            " cart2(a/b)=" & std_logic'image(cart2_active) & std_logic'image(cart2_busy) &
            " cart_ena=" & std_logic'image(cart_ena) &
            " c1_pc=0x" & to_hstring(c1_export.pc) &
            " c2_pc=0x" & to_hstring(c2_export.pc)
            severity error;
      end procedure;
   begin

      ew1_watch : process (clk1x)
         variable cnt : integer := 0;
      begin
         if rising_edge(clk1x) then
            if (ewram_ena = '1') then cnt := 1;
            elsif (ewram_done = '1') then cnt := 0;
            elsif (cnt > 0) then
               cnt := cnt + 1;
               if (cnt = HANG_CYCLES) then
                  dump_arb("HANG core1 EWRAM addr=0x" & to_hstring(unsigned(ewram_addr)) & " rnw=" & std_logic'image(ewram_rnw));
                  report "core1 EWRAM handshake never completed" severity failure;
               end if;
            end if;
         end if;
      end process;

      ew2_watch : process (clk1x)
         variable cnt : integer := 0;
      begin
         if rising_edge(clk1x) then
            if (ew2_ena = '1') then cnt := 1;
            elsif (ew2_done = '1') then cnt := 0;
            elsif (cnt > 0) then
               cnt := cnt + 1;
               if (cnt = HANG_CYCLES) then
                  dump_arb("HANG core2 EWRAM addr=0x" & to_hstring(unsigned(ew2_addr)) & " rnw=" & std_logic'image(ew2_rnw));
                  report "core2 EWRAM handshake never completed" severity failure;
               end if;
            end if;
         end if;
      end process;

      cart1_watch : process (clk1x)
         variable cnt : integer := 0;
      begin
         if rising_edge(clk1x) then
            if (cart_ena = '1') then cnt := 1;
            elsif (cart_done = '1') then cnt := 0;
            elsif (cnt > 0) then
               cnt := cnt + 1;
               if (cnt = HANG_CYCLES) then
                  dump_arb("HANG core1 cart addr=0x" & to_hstring(unsigned(cart_addr)) & " rnw=" & std_logic'image(cart_rnw));
                  report "core1 cart handshake never completed" severity failure;
               end if;
            end if;
         end if;
      end process;

      cart2_watch : process (clk1x)
         variable cnt : integer := 0;
      begin
         if rising_edge(clk1x) then
            if (c2_cart_ena = '1') then cnt := 1;
            elsif (c2_cart_done = '1') then cnt := 0;
            elsif (cnt > 0) then
               cnt := cnt + 1;
               if (cnt = HANG_CYCLES) then
                  dump_arb("HANG core2 cart addr=0x" & to_hstring(unsigned(c2_cart_addr)) & " rnw=" & std_logic'image(c2_cart_rnw));
                  report "core2 cart handshake never completed" severity failure;
               end if;
            end if;
         end if;
      end process;

   end block;

   -- ==================================================================
   -- progress trace
   -- ==================================================================
   progress : process
   begin
      wait until GBA_on = '1';
      report "reset released, cores running";
      loop
         wait until rising_edge(c1_vblank) for 60 ms;
         exit when not (c1_vblank'event);
         report "core1 vblank, pc=0x" & to_hstring(c1_export.pc) &
                "  core2 pc=0x" & to_hstring(c2_export.pc);
      end loop;
      report "progress watchdog: no core1 vblank within timeout window" severity warning;
      wait;
   end process;

   heartbeat : process
   begin
      wait until GBA_on = '1';
      loop
         wait for 1 ms;
         report "pc trace: core1=0x" & to_hstring(c1_export.pc) &
                "  core2=0x" & to_hstring(c2_export.pc);
      end loop;
   end process;

   -- frame-paint detection: the hardware crash happened right after core 1's
   -- first painted frame, so log every completed 160-line paint per core
   paint_watch : process (clk1x)
      variable f1, f2 : integer := 0;
   begin
      if rising_edge(clk1x) then
         if (c1_px_we = '1' and c1_px_x = 239 and c1_px_y = 159) then
            f1 := f1 + 1;
            report "core1 PAINTED frame " & integer'image(f1) & " @ " & time'image(now);
         end if;
         if (c2_px_we = '1' and c2_px_x = 239 and c2_px_y = 159) then
            f2 := f2 + 1;
            report "core2 PAINTED frame " & integer'image(f2) & " @ " & time'image(now);
         end if;
      end if;
   end process;

   refresh_watch : process (clk6x)
   begin
      if rising_edge(clk6x) then
         assert error_refresh = '0'
            report "memorymux_extern error_refresh raised (refresh starved > timer)" severity warning;
      end if;
   end process;

end architecture;
