-- SPDX-License-Identifier: GPL-3.0-or-later
-- SPDX-FileCopyrightText: 2026 Sarah Aronson <v@pingas.org>
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;
use IEEE.std_logic_textio.all;

use work.pProc_bus_gba.all;

-- CPU-level link-cable confidence check: boots the real homebrew demo
-- sim/tests/LinkCable_basic.gba (afska/gba-link-connection v8.0.3) on two
-- gba_top cores wired cable-to-cable exactly like the internal 2P link
-- (rtl/gba_wrap.vhd ~975-993: wired-AND SC/SD, crossed SO/SI, registered on
-- clk1x), each fed by a behavioral cart model reading the same ROM file and
-- a real 16KB BIOS image (sim/tests/bios_words.hex, generated by the run
-- script from $GBA_BIOS -- use a fast-boot BIOS to skip the logo animation).
--
-- Pass criterion: decode the Multi-Player SIO frames on the shared SD line
-- and show both cores' demo counters actually incrementing and flowing in
-- both directions -- not just that registers toggle.
--
-- run: sim/run_link2p_cpu_tb.sh

entity tb_link2p_cpu is
end entity;

architecture sim of tb_link2p_cpu is

   constant CLK_PERIOD : time := 10 ns; -- 100 MHz sim clock == gba_top's clk1x

   signal clk  : std_logic := '0';
   signal done : boolean   := false;

   -- ------------------------------------------------------------------
   -- BIOS stub, loaded into both cores identically via bios_wr* at time 0
   -- ------------------------------------------------------------------
   constant BIOS_WORDS : integer := 4096; -- full 16KB BIOS

   type t_word_array is array (natural range <>) of std_logic_vector(31 downto 0);

   impure function load_hexfile(path : string; max_words : integer) return t_word_array is
      file     f       : text;
      variable ln      : line;
      variable words   : t_word_array(0 to max_words - 1) := (others => (others => '0'));
      variable i       : integer := 0;
      variable hexword : std_logic_vector(31 downto 0);
      variable ok      : boolean;
   begin
      file_open(f, path, read_mode);
      while not endfile(f) and i < max_words loop
         readline(f, ln);
         hread(ln, hexword, ok);
         assert ok report "hread failed on " & path severity failure;
         words(i) := hexword;
         i := i + 1;
      end loop;
      file_close(f);
      report path & ": loaded " & integer'image(i) & " words";
      return words;
   end function;

   -- ------------------------------------------------------------------
   -- cart ROM, shared image loaded once, served independently to each core
   -- ------------------------------------------------------------------
   constant ROM_WORDS : integer := 9958; -- LinkCable_basic.gba size / 4

   shared variable rom_image  : t_word_array(0 to ROM_WORDS - 1);
   shared variable bios_image : t_word_array(0 to BIOS_WORDS - 1);

   -- ------------------------------------------------------------------
   -- per-core signals
   -- ------------------------------------------------------------------
   type t_core_io is record
      cart_ena       : std_logic;
      cart_rnw       : std_logic;
      cart_addr      : std_logic_vector(27 downto 0);
      cart_writedata : std_logic_vector(7 downto 0);
      cart_done      : std_logic;
      cart_readdata  : std_logic_vector(31 downto 0);
   end record;

   signal c1, c2 : t_core_io;

   signal bios_wraddr : std_logic_vector(11 downto 0) := (others => '0');
   signal bios_wrdata : std_logic_vector(31 downto 0) := (others => '0');
   signal bios_wr     : std_logic := '0';

   signal GBA_on : std_logic := '0';

   -- link port signals, (value, oe) pairs per core, cross-wired like
   -- gba_wrap.vhd's internal 2P link (core1 = parent)
   signal c1_link_clk_out, c1_link_clk_oe, c1_link_clk_in : std_logic;
   signal c1_link_so_out,  c1_link_so_oe,  c1_link_si_in  : std_logic;
   signal c1_link_sd_out,  c1_link_sd_oe,  c1_link_sd_in  : std_logic;

   signal c2_link_clk_out, c2_link_clk_oe, c2_link_clk_in : std_logic;
   signal c2_link_so_out,  c2_link_so_oe,  c2_link_si_in  : std_logic;
   signal c2_link_sd_out,  c2_link_sd_oe,  c2_link_sd_in  : std_logic;

   signal l_sc, l_sd, l_si_c1, l_si_c2 : std_logic := '1';

   signal c1_vblank, c2_vblank : std_logic;
   signal c1_pc, c2_pc         : std_logic_vector(31 downto 0);

   -- real CPU state, pulled from inside each core (VHDL-2008 external names,
   -- resolved in the monitor block below after the cores have elaborated;
   -- the debug_cpu_pc port is only driven by gba_wrap, not gba_top)
   signal c1_export, c2_export : work.pexport.cpu_export_type;

   constant ZERO28 : std_logic_vector(27 downto 0) := (others => '0');
   constant ZERO32 : std_logic_vector(31 downto 0) := (others => '0');
   constant ZERO64 : std_logic_vector(63 downto 0) := (others => '0');

   -- ------------------------------------------------------------------
   -- SIO wire decoder: watches the shared SD line for Multi-Player frames
   -- and reconstructs the 16-bit words each end actually put on the wire,
   -- the same LSB-first sampling technique sim/tb_link.vhd's cap_bits
   -- process uses, but free-running (captures every frame, not just an
   -- armed one-shot) and printed via `report` for a human-readable trace.
   -- ------------------------------------------------------------------
   signal sio_frame_count : integer := 0;

   -- ------------------------------------------------------------------
   -- framebuffer dump: core1's rendered frames written as ASCII PGM so the
   -- demo's on-screen text ("Players: N") can be read directly from the
   -- sim, closing the interpretation gap between wire traces and what the
   -- software actually displays. One file per frame, grayscale from RGB555.
   -- ------------------------------------------------------------------
   signal c1_px_x    : integer range 0 to 239;
   signal c1_px_y    : integer range 0 to 159;
   signal c1_px_data : std_logic_vector(14 downto 0);
   signal c1_px_we   : std_logic;

begin

   clk <= not clk after CLK_PERIOD / 2 when not done else '0';

   -- ==================================================================
   -- BIOS + ROM image loading (simulation-time only, not synthesizable)
   -- ==================================================================
   preload : process
   begin
      rom_image  := load_hexfile("sim/tests/rom_words.hex", ROM_WORDS);
      bios_image := load_hexfile("sim/tests/bios_words.hex", BIOS_WORDS);
      wait;
   end process;

   -- drive bios_wr* once at the start for both cores (shared bus, both
   -- gba_top instances see the same bios_wraddr/bios_wrdata/bios_wr)
   biosload : process
      variable i : integer;
   begin
      wait for 100 ns;
      wait until rising_edge(clk);
      for i in 0 to BIOS_WORDS - 1 loop
         bios_wraddr <= std_logic_vector(to_unsigned(i, 12));
         bios_wrdata <= bios_image(i);
         bios_wr     <= '1';
         wait until rising_edge(clk);
      end loop;
      bios_wr <= '0';
      report "BIOS loaded into both cores";

      -- power-on reset after BIOS is in place
      wait for 100 ns;
      GBA_on <= '1';
      wait;
   end process;

   -- ==================================================================
   -- behavioral cart models: serve 32-bit words from rom_image, modeling
   -- a fixed few-cycle latency like real cart_done handshaking (waitstates
   -- inside gba_memorymux are layered on top of this independently)
   -- ==================================================================
   cart1 : process (clk)
      variable idx : integer;
   begin
      if rising_edge(clk) then
         c1.cart_done <= '0';
         if (c1.cart_ena = '1') then
            idx := to_integer(unsigned(c1.cart_addr(23 downto 2)));
            if (idx < ROM_WORDS) then
               c1.cart_readdata <= rom_image(idx);
            else
               c1.cart_readdata <= x"FFFFFFFF"; -- open bus past ROM end
            end if;
            c1.cart_done <= '1';
         end if;
      end if;
   end process;

   cart2 : process (clk)
      variable idx : integer;
   begin
      if rising_edge(clk) then
         c2.cart_done <= '0';
         if (c2.cart_ena = '1') then
            idx := to_integer(unsigned(c2.cart_addr(23 downto 2)));
            if (idx < ROM_WORDS) then
               c2.cart_readdata <= rom_image(idx);
            else
               c2.cart_readdata <= x"FFFFFFFF";
            end if;
            c2.cart_done <= '1';
         end if;
      end if;
   end process;

   -- ==================================================================
   -- cross-wired internal link cable: identical pattern to
   -- rtl/gba_wrap.vhd's registered wired-AND SC/SD + crossed SO/SI
   -- (core 1 = parent, core 2 = child)
   -- ==================================================================
   process (clk)
   begin
      if rising_edge(clk) then
         l_sc    <= (c1_link_clk_out or not c1_link_clk_oe) and (c2_link_clk_out or not c2_link_clk_oe);
         l_sd    <= (c1_link_sd_out  or not c1_link_sd_oe ) and (c2_link_sd_out  or not c2_link_sd_oe );
         l_si_c1 <= '0'; -- real cable: 1P plug grounds SI (that's what makes core 1 the master)
         l_si_c2 <= (c1_link_so_out  or not c1_link_so_oe );
      end if;
   end process;

   c1_link_clk_in <= l_sc;
   c1_link_si_in  <= l_si_c1;
   c1_link_sd_in  <= l_sd;
   c2_link_clk_in <= l_sc;
   c2_link_si_in  <= l_si_c2;
   c2_link_sd_in  <= l_sd;

   -- both ends actively driving SD low at once is a protocol violation,
   -- exactly the standing assertion sim/tb_link.vhd carries
   process (clk)
   begin
      if rising_edge(clk) then
         assert not (c1_link_sd_oe = '1' and c1_link_sd_out = '0' and
                     c2_link_sd_oe = '1' and c2_link_sd_out = '0')
            report "SD driven low by both cores simultaneously" severity failure;
      end if;
   end process;

   -- ==================================================================
   -- two gba_top cores
   -- ==================================================================
   icore1 : entity work.gba_top
   generic map
   (
      Softmap_GBA_Gamerom_ADDR => 0,
      Softmap_GBA_FLASH_ADDR   => 0,
      Softmap_GBA_EEPROM_ADDR  => 0,
      Softmap_SaveState_ADDR   => 0,
      Softmap_Rewind_ADDR      => 0,
      is_simu                  => '1',
      simu_export_trace        => '0',
      strip_savestates         => '1',
      strip_cheats             => '1',
      ewram_in_sdram           => '0',
      turbosound               => '0'
   )
   port map
   (
      clk1x                 => clk,
      GBA_on                => GBA_on,
      pause                 => '0',
      allowUnpause          => '1',
      inPause               => open,
      GBA_lockspeed         => '1',
      GBA_cputurbo          => '0',
      GBA_flash_1m          => '0',
      Underclock            => "00",
      CyclesMissing         => open,
      CyclesVsyncSpeed      => open,
      increaseSSHeaderCount => '0',
      save_state            => '0',
      load_state            => '0',
      interframe_blend      => "00",
      shade_mode            => "000",
      rewind_on             => '0',
      rewind_active         => '0',
      savestate_number      => 0,

      error_cpu             => open,
      error_memRequ_timeout => open,
      error_memResp_timeout => open,
      flash_busy            => '0',

      cheat_clear           => '0',
      cheats_enabled        => '0',
      cheat_on              => '0',
      cheat_in              => (others => '0'),
      cheats_active         => open,

      cart_ena              => c1.cart_ena,
      cart_idle             => open,
      cart_32               => open,
      cart_rnw              => c1.cart_rnw,
      cart_addr             => c1.cart_addr,
      cart_writedata        => c1.cart_writedata,
      cart_done             => c1.cart_done,
      cart_readdata         => c1.cart_readdata,
      cart_waitcnt          => open,
      dma_eepromcount       => open,
      cart_reset            => open,

      ewram_ena             => open,
      ewram_rnw             => open,
      ewram_addr            => open,
      ewram_be              => open,
      ewram_writedata       => open,
      ewram_done            => '0',
      ewram_readdata        => (others => '0'),

      SAVE_out_Din          => open,
      SAVE_out_Dout         => ZERO64,
      SAVE_out_Adr          => open,
      SAVE_out_rnw          => open,
      SAVE_out_ena          => open,
      SAVE_out_active       => open,
      SAVE_out_be           => open,
      SAVE_out_done         => '0',
      savestate_bus_ext     => open,
      ss_wired_out_ext      => ZERO32,
      ss_wired_done_ext     => '0',

      bios_wraddr           => bios_wraddr,
      bios_wrdata           => bios_wrdata,
      bios_wr               => bios_wr,

      load_done             => open,

      KeyA                  => '0',
      KeyB                  => '0',
      KeySelect             => '0',
      KeyStart              => '0',
      KeyRight              => '0',
      KeyLeft               => '0',
      KeyUp                 => '0',
      KeyDown               => '0',
      KeyR                  => '0',
      KeyL                  => '0',
      KeyPause              => '0',

      link_enable           => '1',
      link_clk_out          => c1_link_clk_out,
      link_clk_oe           => c1_link_clk_oe,
      link_clk_in           => c1_link_clk_in,
      link_so_out           => c1_link_so_out,
      link_so_oe            => c1_link_so_oe,
      link_si_in            => c1_link_si_in,
      link_sd_out           => c1_link_sd_out,
      link_sd_oe            => c1_link_sd_oe,
      link_sd_in            => c1_link_sd_in,

      GBA_BusAddr           => ZERO28,
      GBA_BusRnW            => '1',
      GBA_BusACC            => "01",
      GBA_BusWriteData      => ZERO32,
      GBA_BusReadData       => open,
      GBA_Bus_written       => '0',

      pixel_out_x           => c1_px_x,
      pixel_out_y           => c1_px_y,
      pixel_out_addr        => open,
      pixel_out_data        => c1_px_data,
      pixel_out_we          => c1_px_we,
      vblank_trigger        => c1_vblank,

      sound_out_left        => open,
      sound_out_right       => open,

      debug_cpu_pc          => c1_pc,
      debug_cpu_mixed       => open,
      debug_irq             => open,
      debug_dma             => open,
      debug_mem             => open
   );

   icore2 : entity work.gba_top
   generic map
   (
      Softmap_GBA_Gamerom_ADDR => 0,
      Softmap_GBA_FLASH_ADDR   => 0,
      Softmap_GBA_EEPROM_ADDR  => 0,
      Softmap_SaveState_ADDR   => 0,
      Softmap_Rewind_ADDR      => 0,
      is_simu                  => '1',
      simu_export_trace        => '0',
      strip_savestates         => '1',
      strip_cheats             => '1',
      ewram_in_sdram           => '0',
      turbosound               => '0'
   )
   port map
   (
      clk1x                 => clk,
      GBA_on                => GBA_on,
      pause                 => '0',
      allowUnpause          => '1',
      inPause               => open,
      GBA_lockspeed         => '1',
      GBA_cputurbo          => '0',
      GBA_flash_1m          => '0',
      Underclock            => "00",
      CyclesMissing         => open,
      CyclesVsyncSpeed      => open,
      increaseSSHeaderCount => '0',
      save_state            => '0',
      load_state            => '0',
      interframe_blend      => "00",
      shade_mode            => "000",
      rewind_on             => '0',
      rewind_active         => '0',
      savestate_number      => 0,

      error_cpu             => open,
      error_memRequ_timeout => open,
      error_memResp_timeout => open,
      flash_busy            => '0',

      cheat_clear           => '0',
      cheats_enabled        => '0',
      cheat_on              => '0',
      cheat_in              => (others => '0'),
      cheats_active         => open,

      cart_ena              => c2.cart_ena,
      cart_idle             => open,
      cart_32               => open,
      cart_rnw              => c2.cart_rnw,
      cart_addr             => c2.cart_addr,
      cart_writedata        => c2.cart_writedata,
      cart_done             => c2.cart_done,
      cart_readdata         => c2.cart_readdata,
      cart_waitcnt          => open,
      dma_eepromcount       => open,
      cart_reset            => open,

      ewram_ena             => open,
      ewram_rnw             => open,
      ewram_addr            => open,
      ewram_be              => open,
      ewram_writedata       => open,
      ewram_done            => '0',
      ewram_readdata        => (others => '0'),

      SAVE_out_Din          => open,
      SAVE_out_Dout         => ZERO64,
      SAVE_out_Adr          => open,
      SAVE_out_rnw          => open,
      SAVE_out_ena          => open,
      SAVE_out_active       => open,
      SAVE_out_be           => open,
      SAVE_out_done         => '0',
      savestate_bus_ext     => open,
      ss_wired_out_ext      => ZERO32,
      ss_wired_done_ext     => '0',

      bios_wraddr           => bios_wraddr,
      bios_wrdata           => bios_wrdata,
      bios_wr               => bios_wr,

      load_done             => open,

      KeyA                  => '0',
      KeyB                  => '0',
      KeySelect             => '0',
      KeyStart              => '0',
      KeyRight              => '0',
      KeyLeft               => '0',
      KeyUp                 => '0',
      KeyDown               => '0',
      KeyR                  => '0',
      KeyL                  => '0',
      KeyPause              => '0',

      link_enable           => '1',
      link_clk_out          => c2_link_clk_out,
      link_clk_oe           => c2_link_clk_oe,
      link_clk_in           => c2_link_clk_in,
      link_so_out           => c2_link_so_out,
      link_so_oe            => c2_link_so_oe,
      link_si_in            => c2_link_si_in,
      link_sd_out           => c2_link_sd_out,
      link_sd_oe            => c2_link_sd_oe,
      link_sd_in            => c2_link_sd_in,

      GBA_BusAddr           => ZERO28,
      GBA_BusRnW            => '1',
      GBA_BusACC            => "01",
      GBA_BusWriteData      => ZERO32,
      GBA_BusReadData       => open,
      GBA_Bus_written       => '0',

      pixel_out_x           => open,
      pixel_out_y           => open,
      pixel_out_addr        => open,
      pixel_out_data        => open,
      pixel_out_we          => open,
      vblank_trigger        => c2_vblank,

      sound_out_left        => open,
      sound_out_right       => open,

      debug_cpu_pc          => c2_pc,
      debug_cpu_mixed       => open,
      debug_irq             => open,
      debug_dma             => open,
      debug_mem             => open
   );

   -- bind the internal cpu state records now that both cores exist
   monitor_bind : block
   begin
      c1_export <= << signal .tb_link2p_cpu.icore1.cpu_export : work.pexport.cpu_export_type >>;
      c2_export <= << signal .tb_link2p_cpu.icore2.cpu_export : work.pexport.cpu_export_type >>;
   end block;

   -- ==================================================================
   -- SIO wire decoder: Multi-Player mode sends 16 bits LSB-first on SD,
   -- start-gated by SC going low (busy line held by whichever end is
   -- driving). We just watch for SD's falling edge (start bit) then sample
   -- 16 bits at the fastest configured baud (145 ce ticks = 115200) --
   -- LinkCable.hpp always configures the fastest baud, matching
   -- sim/tb_link.vhd test 5's replay of its exact register choreography.
   -- ==================================================================
   sio_decode : process
      variable bits    : std_logic_vector(15 downto 0);
      variable k       : integer;
      variable cecount : integer;
   begin
      wait until GBA_on = '1';
      loop
         wait until falling_edge(l_sd);
         for k in 0 to 15 loop
            wait for 145 * CLK_PERIOD; -- one bit period at 115200 baud
            bits(k) := l_sd;
         end loop;
         sio_frame_count <= sio_frame_count + 1;
         report "SIO frame #" & integer'image(sio_frame_count) &
                " @ " & time'image(now) & " : 0x" &
                to_hstring(bits);
      end loop;
   end process;

   -- ==================================================================
   -- run control / progress trace
   -- ==================================================================
   progress : process
   begin
      wait until GBA_on = '1';
      report "reset released, cores running";
      loop
         wait until rising_edge(c1_vblank) for 50 ms;
         exit when not (c1_vblank'event);
         report "core1 vblank, pc=0x" & to_hstring(c1_export.pc) &
                "  core2 pc=0x" & to_hstring(c2_export.pc);
      end loop;
      report "progress watchdog: no core1 vblank within timeout window" severity warning;
      wait;
   end process;

   -- catch the first metavalue reaching either program counter, with the
   -- last known-good pc for orientation
   xwatch : process (clk)
      variable c1_lastpc, c2_lastpc : unsigned(31 downto 0) := (others => '0');
      variable tripped              : boolean := false;
   begin
      if rising_edge(clk) and GBA_on = '1' and not tripped then
         if is_x(std_logic_vector(c1_export.pc)) or is_x(std_logic_vector(c2_export.pc)) then
            report "X reached cpu pc: core1=0x" & to_hstring(c1_export.pc) &
                   " (last 0x" & to_hstring(c1_lastpc) & ")" &
                   "  core2=0x" & to_hstring(c2_export.pc) &
                   " (last 0x" & to_hstring(c2_lastpc) & ")"
               severity error;
            tripped := true;
         else
            c1_lastpc := c1_export.pc;
            c2_lastpc := c2_export.pc;
         end if;
      end if;
   end process;

   -- coarse PC heartbeat so a hung boot is diagnosable without a wave dump
   heartbeat : process
   begin
      wait until GBA_on = '1';
      loop
         wait for 250 us;
         report "pc trace: core1=0x" & to_hstring(c1_export.pc) &
                "  core2=0x" & to_hstring(c2_export.pc);
      end loop;
   end process;

   -- see the declaration comment: dump each finished core1 frame as an
   -- ASCII PGM (grayscale = summed RGB555 channels) so the demo's screen
   -- text is directly readable from the sim output directory
   framedump : process (clk)
      type t_fb is array (0 to 159, 0 to 239) of integer range 0 to 93;
      variable fb        : t_fb;
      variable frame_n   : integer := 0;
      variable seen_px   : boolean := false;
      file     fout      : text;
      variable l         : line;
   begin
      if rising_edge(clk) then
         if (c1_px_we = '1') then
            fb(c1_px_y, c1_px_x) :=
               to_integer(unsigned(c1_px_data(14 downto 10))) +
               to_integer(unsigned(c1_px_data( 9 downto  5))) +
               to_integer(unsigned(c1_px_data( 4 downto  0)));
            seen_px := true;
            if (c1_px_y = 159 and c1_px_x = 239) then
               file_open(fout, "sim/tests/frame_c1_" & integer'image(frame_n) & ".pgm", write_mode);
               write(l, string'("P2")); writeline(fout, l);
               write(l, string'("240 160")); writeline(fout, l);
               write(l, string'("93")); writeline(fout, l);
               for y in 0 to 159 loop
                  for x in 0 to 239 loop
                     write(l, integer'image(fb(y, x)));
                     if (x /= 239) then write(l, string'(" ")); end if;
                  end loop;
                  writeline(fout, l);
               end loop;
               file_close(fout);
               report "frame_c1_" & integer'image(frame_n) & ".pgm written";
               frame_n := frame_n + 1;
            end if;
         end if;
      end if;
   end process;

end architecture;
